image:
  name: hashicorp/terraform:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' 
    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' 
    - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'

variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform

before_script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - case "$CI_COMMIT_REF_SLUG" in 
      master) WORKSPACE="prod" ;;
        *) WORKSPACE="dev" ;;
      esac
  - rm -rf .terraform
  - terraform --version
  - git config --global url."https://jose-manuel.sanchez:wD_WmshQMjptvv2reL3U@innersource.soprasteria.com".insteadOf https://innersource.soprasteria.com
  - terraform init
  - terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=$PLAN
  dependencies:
    - validate     
  artifacts:
    name: plan
    paths:
      - $PLAN

apply:
  stage: apply
  script:
    - terraform apply -input=false $PLAN
  dependencies:
    - plan


destroy:
  stage: destroy
  script:
    - echo "Destroying resources"
    - terraform destroy -state=$STATE --auto-approve
  dependencies:
    - apply  
  when: manual
